[package]
name = "re-sourcer-tray"
version = "0.2.4"
description = "ReSourcer 系统托盘应用"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-cli = "2"

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
